"use client";
import { useMemo, useState } from "react";
import { Building2, Check, LocateFixed, Map, MapPin, Search, SlidersHorizontal } from "lucide-react";
import { statusColor, type Project, type ProjectStatus } from "@/lib/brickline-data";
import { projectMapLocation } from "@/lib/project-map";
import { findRegionForArea, indiaRegions } from "@/lib/india-areas";
import { EmptyState, PageHeader } from "../ui";

const statuses:ProjectStatus[]=["New construction","Redevelopment","Approval stage","Construction started"];
export function MapView({items,onProject,onNotify}:{items:Project[];onProject:(id:string)=>void;onNotify:(m:string)=>void}){
 const [query,setQuery]=useState(""),[selected,setSelected]=useState("All India"),[enabled,setEnabled]=useState<ProjectStatus[]>(statuses),[mapMode,setMapMode]=useState<"google"|"coverage">("google"),[focusedProjectId,setFocusedProjectId]=useState<string|null>(null);
 const regionResults=useMemo(()=>indiaRegions.filter(region=>`${region.name} ${region.capital} ${region.cities.join(" ")}`.toLowerCase().includes(query.toLowerCase())),[query]);
 const visibleProjects=useMemo(()=>items.filter(project=>{const region=findRegionForArea(project.area);return enabled.includes(project.status)&&(selected==="All India"||region?.name===selected||project.area.includes(selected))&&`${project.name} ${project.area} ${project.builder}`.toLowerCase().includes(query.toLowerCase())}),[items,enabled,selected,query]);
 const activeRegion=selected==="All India"?null:indiaRegions.find(region=>region.name===selected); const toggle=(s:ProjectStatus)=>setEnabled(v=>v.includes(s)?v.filter(x=>x!==s):[...v,s]); const focusedProject=items.find(project=>project.id===focusedProjectId); const mapQuery=query.trim()||activeRegion?.capital||activeRegion?.name||"India"; const embedUrl=focusedProject?projectMapLocation(focusedProject).embedUrl:`https://maps.google.com/maps?q=${encodeURIComponent(`${mapQuery}, India`)}&z=${activeRegion||query?7:5}&output=embed`;
 return <div className="page map-page"><PageHeader eyebrow="INDIA DEVELOPMENT MAP" title="Development activity across India" description="Explore every state and union territory, then drill into major cities and active projects." actions={<button className="button secondary" onClick={()=>{setSelected("Maharashtra");setQuery("");onNotify("Map centered on Maharashtra")} }><LocateFixed size={16}/>My territory</button>}/>
  <section className="india-map-workspace"><aside className="india-map-sidebar"><div className="search-field"><Search size={17}/><input value={query} onChange={e=>{setQuery(e.target.value);setFocusedProjectId(null)}} placeholder="Search state, city or project"/></div><div className="coverage-total"><b>36</b><span>states and union territories</span><small>{indiaRegions.reduce((sum,region)=>sum+region.cities.length,0)} major cities available</small></div><div className="filter-title"><span>DEVELOPMENT STAGE</span><SlidersHorizontal size={15}/></div>{statuses.map(s=><button className="check-row" key={s} onClick={()=>toggle(s)}><span className={enabled.includes(s)?"checkbox checked":"checkbox"}>{enabled.includes(s)&&<Check size={13}/>}</span><i style={{background:statusColor[s]}}/>{s}<b>{items.filter(p=>p.status===s).length}</b></button>)}<div className="filter-title"><span>AREAS</span><b>{regionResults.length}</b></div><div className="region-list"><button className={selected==="All India"?"active":""} onClick={()=>{setSelected("All India");setFocusedProjectId(null)}}><span className="region-code">IN</span><span><b>All India</b><small>National coverage</small></span></button>{regionResults.map(region=><button className={selected===region.name?"active":""} key={region.code} onClick={()=>{setSelected(region.name);setFocusedProjectId(null)}}><span className="region-code">{region.code}</span><span><b>{region.name}</b><small>{region.type} · {region.cities.length} cities</small></span></button>)}</div></aside>
   <div className="india-map-main">
    <div className="map-provider-bar">
     <div className="map-mode-toggle">
      <button className={mapMode==="google"?"active":""} onClick={()=>setMapMode("google")}><MapPin size={15}/>Google Maps</button>
      <button className={mapMode==="coverage"?"active":""} onClick={()=>setMapMode("coverage")}><Map size={15}/>Coverage view</button>
     </div>
     <span className="map-context">{focusedProject ? `Showing ${focusedProject.siteAddress ? "site" : "area"}: ${focusedProject.name}` : "Map stays inside Brickline"}</span>
    </div>
    {mapMode==="google"?<div className="google-map-frame"><iframe key={embedUrl} title={`Google Map of ${focusedProject?.name||mapQuery}`} src={embedUrl} loading="lazy" referrerPolicy="no-referrer-when-downgrade" allowFullScreen/></div>:<div className="india-map-canvas"><div className="india-silhouette"/>{indiaRegions.map(region=><button title={`${region.name} — ${region.capital}`} aria-label={region.name} className={`${selected===region.name?"india-region-dot active":"india-region-dot"}${region.type==="Union Territory"?" ut":""}`} style={{left:`${region.x}%`,top:`${region.y}%`}} key={region.code} onClick={()=>{setSelected(region.name);setFocusedProjectId(null)}}><span>{region.code}</span></button>)}<div className="india-map-key"><span><i className="state-key"/>State</span><span><i className="ut-key"/>Union territory</span></div></div>}
    <section className="region-detail"><div className="region-detail-head"><div><span className="eyebrow">{activeRegion?.type.toUpperCase()||"NATIONAL COVERAGE"}</span><h2>{activeRegion?.name||"All India"}</h2><p>{activeRegion?`Capital: ${activeRegion.capital}`:"Select any area to view cities and projects."}</p></div><span className="project-count"><Building2 size={17}/><b>{visibleProjects.length}</b> projects</span></div>{activeRegion&&<div className="city-chips">{activeRegion.cities.map(city=><button key={city} onClick={()=>{setQuery(city);setFocusedProjectId(null);setMapMode("google")}}><MapPin size={12}/>{city}</button>)}</div>}<div className="india-project-results">{visibleProjects.map(project=><button key={project.id} onClick={()=>{setFocusedProjectId(project.id);setMapMode("google");onProject(project.id)}}><span className="project-result-icon" style={{background:statusColor[project.status]}}><Building2 size={17}/></span><span><b>{project.name}</b><small>{project.area} · {project.builder}</small></span><span className="status-pill"><i style={{background:statusColor[project.status]}}/>{project.status}</span></button>)}{!visibleProjects.length&&<EmptyState title="No active projects in this view" body="The area remains available for monitoring. Add a project or choose another region."/>}</div></section>
   </div>
  </section>
 </div>
}
