"use client";
import { useMemo, useState } from "react";
import { Check, Layers3, LocateFixed, Search, SlidersHorizontal } from "lucide-react";
import { statusColor, type Project, type ProjectStatus } from "@/lib/brickline-data";
import { EmptyState, PageHeader } from "../ui";
import { MapDecor } from "./overview-view";

const statuses:ProjectStatus[]=["New construction","Redevelopment","Approval stage","Construction started"];
export function MapView({items,onProject,onNotify}:{items:Project[];onProject:(id:string)=>void;onNotify:(m:string)=>void}){const [query,setQuery]=useState(""),[area,setArea]=useState("All Mumbai"),[enabled,setEnabled]=useState<ProjectStatus[]>(statuses),[satellite,setSatellite]=useState(false);const visible=useMemo(()=>items.filter(p=>(area==="All Mumbai"||p.area.includes(area))&&enabled.includes(p.status)&&`${p.name} ${p.area} ${p.builder}`.toLowerCase().includes(query.toLowerCase())),[items,query,area,enabled]);const toggle=(s:ProjectStatus)=>setEnabled(v=>v.includes(s)?v.filter(x=>x!==s):[...v,s]);return <div className="page map-page"><PageHeader eyebrow="DEVELOPMENT MAP" title="Mumbai development activity" description="Explore verified construction, redevelopment and approval signals by area." actions={<button className="button secondary" onClick={()=>onNotify("Map centered on your saved Mumbai territory")}><LocateFixed size={16}/>My territory</button>}/><section className="map-workspace"><aside className="map-sidebar"><div className="search-field"><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search map"/></div><label className="field-label">AREA<select value={area} onChange={e=>setArea(e.target.value)}><option>All Mumbai</option><option>Bandra</option><option>Andheri</option><option>Worli</option><option>Dadar</option><option>Powai</option><option>Sewri</option></select></label><div className="filter-title"><span>DEVELOPMENT STAGE</span><SlidersHorizontal size={15}/></div>{statuses.map(s=><button className="check-row" key={s} onClick={()=>toggle(s)}><span className={enabled.includes(s)?"checkbox checked":"checkbox"}>{enabled.includes(s)&&<Check size={13}/>}</span><i style={{background:statusColor[s]}}/>{s}<b>{items.filter(p=>p.status===s).length}</b></button>)}<div className="map-summary"><b>{visible.length}</b><span>matching projects</span><small>₹{visible.reduce((a,p)=>a+p.value,0).toLocaleString()} Cr combined value</small></div></aside><div className={satellite?"map-canvas full satellite":"map-canvas full"}><MapDecor/><div className="map-tools"><button className={satellite?"active":""} onClick={()=>setSatellite(!satellite)}><Layers3 size={16}/>{satellite?"Standard":"Satellite"}</button></div>{visible.map((p,i)=><button className={`map-pin pin-${i%4}`} style={{left:`${p.coordinates.x}%`,top:`${p.coordinates.y}%`,"--signal":statusColor[p.status]} as React.CSSProperties} key={p.id} onClick={()=>onProject(p.id)}><i/><span><b>{p.name}</b><small>{p.status}</small></span></button>)}{!visible.length&&<div className="map-empty"><EmptyState title="No projects match" body="Change the area or development-stage filters."/></div>}<div className="map-legend">{statuses.map(s=><span key={s}><i style={{background:statusColor[s]}}/>{s}</span>)}</div></div></section></div>}
