"use client";
import { useMemo, useState } from "react";
import { Bookmark, BriefcaseBusiness, MapPin, Search } from "lucide-react";
import type { Opportunity, Role } from "@/lib/brickline-data";
import { EmptyState, PageHeader } from "../ui";

export function MarketplaceView({ items, role, applied, saved, onApply, onSave, onPost }: { items: Opportunity[]; role: Role; applied: Set<string>; saved: Set<string>; onApply: (id: string) => void; onSave: (id: string) => void; onPost: () => void }) {
  const [query, setQuery] = useState(""); const rows = useMemo(() => items.filter(item => `${item.title} ${item.builder} ${item.area} ${item.type}`.toLowerCase().includes(query.toLowerCase())), [items, query]);
  return <div className="page"><PageHeader eyebrow="INDIA OPPORTUNITIES" title={role === "Agent" ? "Find builder mandates" : role === "Builder" ? "Reach verified agents" : "Explore market opportunities"} description="Builder-posted opportunities across Indian markets." actions={role === "Builder" ? <button className="button primary" onClick={onPost}>Post opportunity</button> : undefined}/><div className="toolbar"><div className="search-field"><Search size={17}/><input value={query} onChange={event => setQuery(event.target.value)} placeholder="Search opportunity, builder, or locality"/></div></div><div className="opportunity-list">{rows.map((item, index) => <article className="opportunity-row" key={item.id}><div className="opportunity-rank">{String(index + 1).padStart(2, "0")}</div><div className="opportunity-copy"><span className="type-pill"><BriefcaseBusiness size={13}/>{item.type}</span><h2>{item.title}</h2><p>{item.description}</p><div className="opportunity-meta"><span><b>{item.builder}</b></span><span><MapPin size={14}/>{item.area}</span></div></div><div className="opportunity-terms"><small>Partner commission</small><b>{item.commission}</b>{role === "Agent" && <button className={applied.has(item.id) ? "button primary applied" : "button primary"} onClick={() => onApply(item.id)}>{applied.has(item.id) ? "Interest recorded" : "Express interest"}</button>}<button className={saved.has(item.id) ? "save-text saved" : "save-text"} onClick={() => onSave(item.id)}><Bookmark size={15}/>{saved.has(item.id) ? "Saved" : "Save"}</button></div></article>)}{!rows.length && <EmptyState title="No opportunities yet" body="Verified Builder opportunities will appear here."/>}</div></div>;
}
