"use client";
import { ArrowUpRight, Bell, Building2, ChevronRight, MapPin, TrendingUp, Users } from "lucide-react";
import { projects, statusColor, type Role, type ViewId } from "@/lib/brickline-data";
import { PageHeader } from "../ui";

export function OverviewView({role,brief,onBrief,onNavigate,onProject,onNotify}:{role:Role;brief:boolean;onBrief:()=>void;onNavigate:(v:ViewId)=>void;onProject:(id:string)=>void;onNotify:(m:string)=>void}){
 const title=role==="Agent"?"Your market is moving":"Your next distribution edge";
 const description=role==="Agent"?"14 development signals are ready to act on across Mumbai.":"21 qualified agents are actively seeking projects in your target zones.";
 return <div className="page"><PageHeader eyebrow="MONDAY, 21 SEPTEMBER" title={title} description={description} actions={<button className={brief?"button secondary subscribed":"button secondary"} onClick={onBrief}><Bell size={16}/>{brief?"Brief subscribed":"Get weekly brief"}</button>}/>
  <section className="metric-grid"><article className="radar-summary"><div><span className="eyebrow">REAL ESTATE RADAR</span><h2>12 fresh signals this week</h2><p>Four high-confidence changes need your attention.</p></div><button onClick={()=>onNavigate("radar")}>Open radar <ArrowUpRight size={16}/></button><div className="wave"><i/><i/><i/><i/><i/><i/><i/></div><div className="signal-counts"><span><b>4</b> New construction</span><span><b>3</b> Redevelopment</span><span><b>5</b> Approvals</span></div></article><article className="metric"><span className="metric-symbol green-soft"><TrendingUp size={20}/></span><small>Market opportunity</small><h2>₹1,385 Cr</h2><p><b>↑ 18%</b> potential launch value</p></article><article className="metric"><span className="metric-symbol blue-soft"><Users size={20}/></span><small>Active network</small><h2>248</h2><p><b>36</b> active in your areas</p></article></section>
  <section className="panel map-preview-panel"><div className="panel-head"><div><span className="eyebrow">DEVELOPMENT INTELLIGENCE</span><h2>What’s changing near you</h2></div><button className="button secondary" onClick={()=>onNavigate("map")}><MapPin size={16}/>Open full map</button></div><div className="map-canvas compact"><MapDecor/>{projects.slice(0,4).map((p,i)=><button className={`map-pin pin-${i}`} style={{left:`${p.coordinates.x}%`,top:`${p.coordinates.y}%`,"--signal":statusColor[p.status]} as React.CSSProperties} key={p.id} onClick={()=>onProject(p.id)}><i/><span><b>{p.name}</b><small>{p.status}</small></span></button>)}</div></section>
  <section className="dashboard-bottom"><div className="panel"><div className="panel-head"><div><span className="eyebrow">PROJECTS</span><h2>Signals worth a closer look</h2></div><button className="link-button" onClick={()=>onNavigate("projects")}>View all <ChevronRight size={16}/></button></div><div className="project-rows">{projects.slice(0,4).map(p=><button className="project-row" key={p.id} onClick={()=>onProject(p.id)}><span className="project-monogram" style={{background:statusColor[p.status]}}>{p.name.split(" ").map(x=>x[0]).join("").slice(0,2)}</span><span><b>{p.name}</b><small>{p.area} · {p.builder}</small></span><span className="status"><i style={{background:statusColor[p.status]}}/>{p.status}</span><span className="value"><b>₹{p.value} Cr</b><small>{p.homes} homes</small></span><ChevronRight size={17}/></button>)}</div></div><aside className="opportunity-card"><span className="eyebrow">BEST MATCH</span><Building2 size={26}/><h2>{role==="Agent"?"Aurelia needs partners in Bandra":"Three agents fit your launch"}</h2><p>{role==="Agent"?"You match their location, luxury category and active buyer profile.":"They have verified buyers, relevant area coverage and strong closure history."}</p><div className="avatar-stack"><i>AK</i><i>RN</i><i>JP</i><span>+6 matches</span></div><button className="button primary" onClick={()=>onNavigate("marketplace")}>Explore opportunity</button><button className="link-button centered" onClick={()=>onNotify("Opportunity saved to your shortlist")}>Save for later</button></aside></section>
 </div>
}
export function MapDecor(){return <><div className="map-water water-one"/><div className="map-water water-two"/><div className="map-road road-one"/><div className="map-road road-two"/><div className="map-road road-three"/><span className="map-place place-one">BANDRA</span><span className="map-place place-two">ANDHERI</span><span className="map-place place-three">WORLI</span></>}
