"use client";

import { useEffect, useState } from "react";
import { BriefcaseBusiness, Check, Globe2, House, Pencil, ShieldCheck, Users } from "lucide-react";
import type { Role } from "@/lib/brickline-data";
import { PageHeader } from "../ui";

export function ProfileView({ role, allowedRoles, verificationLabel, verifiedAt, onRoleChange, onNotify }: { role: Role; allowedRoles: Role[]; verificationLabel: string | null; verifiedAt: number | null; onRoleChange: (role: Role) => void; onNotify: (message: string) => void }) {
  const [editing, setEditing] = useState(false); const [name, setName] = useState(""); const [company, setCompany] = useState(""); const [markets, setMarkets] = useState("");
  useEffect(() => { const timer = window.setTimeout(() => { try { const saved = JSON.parse(localStorage.getItem("brickline-india-profile") || "{}"); setName(saved.name || ""); setCompany(saved.company || ""); setMarkets(saved.markets || ""); } catch { /* invalid local profile */ } }, 0); return () => window.clearTimeout(timer); }, []);
  const save = () => { localStorage.setItem("brickline-india-profile", JSON.stringify({ name, company, markets })); setEditing(false); onNotify("Profile saved on this device"); };
  return <div className="page"><PageHeader eyebrow="YOUR INDIA WORKSPACE" title="Your profile" description="See your verification and the panels assigned to your account." actions={<button className="button primary" onClick={() => editing ? save() : setEditing(true)}>{editing ? <><Check size={16}/>Save profile</> : <><Pencil size={16}/>Edit display details</>}</button>}/><div className="profile-grid"><section className="panel profile-card"><div className="large-avatar"><Globe2 size={34}/></div>{editing ? <><label>Name<input value={name} onChange={event => setName(event.target.value)} placeholder="Your name"/></label><label>Company<input value={company} onChange={event => setCompany(event.target.value)} placeholder="Your company"/></label><label>Markets<input value={markets} onChange={event => setMarkets(event.target.value)} placeholder="Indian states or cities you serve"/></label></> : <><h2>{name || "Your name"}</h2><p>{company || "Add your company"}</p><small>{markets || "Add your India markets"}</small></>}{verificationLabel && <div className="verified-badge" title={`${verificationLabel}${verifiedAt ? ` · checked ${new Date(verifiedAt).toLocaleDateString()}` : ""}`}><ShieldCheck size={15}/><span>{verificationLabel}{verifiedAt && <small>Checked {new Date(verifiedAt).toLocaleDateString()}</small>}</span></div>}</section><section className="panel profile-settings"><span className="eyebrow">SERVER-ENFORCED PANEL ACCESS</span><h2>Your available panels</h2><div className="role-cards">{allowedRoles.includes("Agent") && <button className={role === "Agent" ? "active" : ""} onClick={() => onRoleChange("Agent")}><Users size={22}/><b>Real-estate agent</b><span>India map discovery, builder research, and secure client introductions.</span></button>}{allowedRoles.includes("Builder") && <button className={role === "Builder" ? "active" : ""} onClick={() => onRoleChange("Builder")}><BriefcaseBusiness size={22}/><b>Builder / developer</b><span>Verified profile, RERA projects, and opportunities.</span></button>}{allowedRoles.includes("Client") && <button className={role === "Client" ? "active" : ""} onClick={() => onRoleChange("Client")}><House size={22}/><b>Client</b><span>India map and projects, with private details shared by an agent.</span></button>}</div><p className="profile-note">The admin controls panel permissions. Every protected API checks the saved server permission; changing this dropdown alone cannot grant access.</p></section></div></div>;
}
