"use client";
import { useMemo, useState } from "react";
import { Bookmark, Building2, Grid2X2, List, Plus, Search, SlidersHorizontal } from "lucide-react";
import { statusColor, type Project, type ProjectStatus } from "@/lib/brickline-data";
import { EmptyState, PageHeader } from "../ui";

export function ProjectsView({ items, saved, onProject, onSave, onAdd }: { items: Project[]; saved: Set<string>; onProject: (id: string) => void; onSave: (id: string) => void; onAdd: () => void }) {
  const [query, setQuery] = useState(""); const [status, setStatus] = useState<"All" | ProjectStatus>("All"); const [layout, setLayout] = useState<"grid" | "list">("grid"); const [sort, setSort] = useState("Recently updated");
  const filtered = useMemo(() => items.filter(project => (status === "All" || project.status === status) && `${project.name} ${project.area} ${project.builder}`.toLowerCase().includes(query.toLowerCase())).sort((a, b) => sort === "Highest value" ? b.value - a.value : sort === "Most homes" ? b.homes - a.homes : 0), [items, query, status, sort]);
  return <div className="page"><PageHeader eyebrow="INDIA PROJECT DIRECTORY" title="Projects" description="RERA-registered Indian projects appear here after a verified Builder adds them." actions={<button className="button primary" onClick={onAdd}><Plus size={16}/>Add project</button>}/><div className="toolbar"><div className="search-field"><Search size={17}/><input value={query} onChange={event => setQuery(event.target.value)} placeholder="Search project, builder, city, or state"/></div><select value={status} onChange={event => setStatus(event.target.value as typeof status)}><option>All</option><option>New construction</option><option>Redevelopment</option><option>Approval stage</option><option>Construction started</option></select><select value={sort} onChange={event => setSort(event.target.value)}><option>Recently updated</option><option>Highest value</option><option>Most homes</option></select><div className="view-toggle"><button className={layout === "grid" ? "active" : ""} onClick={() => setLayout("grid")}><Grid2X2 size={16}/></button><button className={layout === "list" ? "active" : ""} onClick={() => setLayout("list")}><List size={17}/></button></div></div><div className="result-bar"><span><SlidersHorizontal size={14}/>{filtered.length} projects</span><button onClick={() => { setQuery(""); setStatus("All"); }}>Clear filters</button></div>{filtered.length ? <div className={layout === "grid" ? "project-grid" : "project-grid list-layout"}>{filtered.map(project => <article className="project-card" key={project.id}><div className="project-visual" style={{ "--project-color": statusColor[project.status] } as React.CSSProperties}><Building2 className="project-visual-icon" size={58}/><button className={saved.has(project.id) ? "save-button saved" : "save-button"} onClick={() => onSave(project.id)}><Bookmark size={17} fill={saved.has(project.id) ? "currentColor" : "none"}/></button><span className="confidence">Registered project</span></div><div className="project-card-body"><div className="status-line"><i style={{ background: statusColor[project.status] }}/>{project.status}<small>{project.updated}</small></div><h2>{project.name}</h2><p>{project.area}, India · {project.builder}</p><div className="project-facts"><span><b>{project.currency || "INR"} {project.value.toLocaleString()}</b>Est. value</span><span><b>{project.homes}</b>Homes</span><span><b>{project.completion}</b>Completion</span></div><button className="button secondary full" onClick={() => onProject(project.id)}><Building2 size={15}/>View project</button></div></article>)}</div> : <EmptyState title="No projects yet" body="Add the first RERA-registered Indian project, or clear your filters."/>}</div>;
}
