import Link from "next/link";
import { PrivacyControls } from "@/components/brickline/privacy-controls";
import { BrandLogo } from "@/components/brickline/brand-logo";

export default function PrivacyPage() {
  return <main className="privacy-page"><header><Link href="/" className="site-brand"><BrandLogo /></Link><Link href="/">Return to workspace</Link></header><article><div className="reference-eyebrow">PRIVACY NOTICE <span>·</span> VERSION 2026-09-23</div><h1>Your information should have a clear purpose.</h1><p className="privacy-lead">This notice describes the information Brickline currently handles, why it is used, how long it is kept, and how you can exercise privacy rights. It is written for the current product—not for features we have not launched.</p>
    <section><h2>Information we currently handle</h2><ul><li>Identity supplied by the sign-in provider: account identifier, name, and verified email.</li><li>Profession, company or agency, registered business address, contact person, phone, requested role, admin approval, and panel permissions.</li><li>Builder/Agent RERA and Builder GST registration numbers. Sensitive numbers are encrypted; one-way keyed fingerprints detect duplicate registrations.</li><li>Registered India project information, including encrypted project RERA numbers.</li><li>Client access grants, expiry, open count, agent, account-bound client, coarse country signal, and a protected device signature.</li><li>Security, admin, and manually verified area-signal activity.</li></ul><p><strong>Not currently collected:</strong> GST documents, identity proofs, RERA certificate files, phone OTP codes, payment data, or uploaded files. Document uploads remain disabled until private storage, malware scanning, and controlled viewing are in place.</p></section>
    <section><h2>Why we use it</h2><p>We use account data to verify roles, operate the three panels, register genuine projects, create time-limited introductions, prevent duplicate or fraudulent registrations, keep an audit trail, respond to privacy requests, and protect the service. We do not use this consent for unrelated marketing.</p></section>
    <section><h2>Choice and control</h2><p>You can request a copy, correction, or deletion below. You may withdraw product-data consent by contacting the administrator; protected panel actions will stop until consent is renewed. Deletion requests are reviewed because some records may need short-term retention for security, dispute, or legal obligations.</p></section>
    <section><h2>Retention schedule</h2><div className="privacy-retention"><span><b>90 days</b>Declined access requests, when no project record depends on them</span><span><b>180 days</b>Expired or revoked client-access grants</span><span><b>365 days</b>Security audit events and completed privacy-request records</span><span><b>Account lifetime</b>Approved accounts and registered projects, until deletion/closure or a required legal hold</span></div><p>Administrators can run the retention cleanup from the Security Audit panel. Pending privacy requests are not automatically deleted.</p></section>
    <section><h2>Storage, sharing, and international access</h2><p>Brickline currently runs on OpenAI Sites and managed Cloudflare infrastructure. An India-only storage region is <strong>not currently guaranteed</strong>. Before a broad India launch or certificate uploads, the owner should select and document an appropriate India-region architecture and vendors. Data is disclosed only to authorized accounts, service infrastructure, or where law requires it.</p></section>
    <section><h2>Security limits</h2><p>Timed links are server-validated, limited to five opens, bound to the intended account and first device signal, and rejected after expiry or revocation. Copy prevention and watermark-style banners are deterrents; no browser control can prevent screenshots. Sign-in verification and login security are handled by the identity provider.</p></section>
    <PrivacyControls/>
    <footer><p>Questions or grievances: <a href="mailto:mohitsonje4@gmail.com">mohitsonje4@gmail.com</a>. This product notice should be reviewed by qualified Indian counsel before commercial launch.</p></footer>
  </article></main>;
}
